### ISSUE TITLE
New grading paper | 2024

### ISSUE THREAD

**Issue by SinaRaoufi** [FDU-VTS/Awesome-Diabetic-Retinopathy-Detection#5]
Please add the following paper:

- Dual Branch Deep Learning Network for Detection and Stage Grading of Diabetic Retinopathy
  [[pdf]](https://www.sciencedirect.com/science/article/pii/S174680942400226X)
  - Hossein Shakibania, Sina Raoufi, Behnam Pourafkham, Hassan Khotanlou, Muharram Mansoorizadeh. *Biomedical Signal Processing and Control*

**Comment by ff741333** [comment]
Thanks for your contribution. We have added it.😊
